# Generated by Codex on 2026-04-08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_outcomes(apps, schema_editor):
    Outcome = apps.get_model("Decision", "Outcome")
    for code in ("FLOAT", "DROWN"):
        Outcome.objects.get_or_create(code=code)


class Migration(migrations.Migration):

    dependencies = [
        ("Decision", "0002_game_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")], default="OPEN", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "rounds"},
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(choices=[("FLOAT", "Float"), ("DROWN", "Drown")], max_length=10, unique=True)),
            ],
            options={"db_table": "outcomes"},
        ),
        migrations.CreateModel(
            name="Phase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase_number", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="phases", to="Decision.decisionround")),
            ],
            options={
                "db_table": "phases",
                "ordering": ["round_id", "phase_number"],
            },
        ),
        migrations.CreateModel(
            name="PhaseCharacterMarket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="markets", to="Decision.character")),
                ("phase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="markets", to="Decision.phase")),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="markets", to="Decision.decisionround")),
            ],
            options={"db_table": "phase_character_market"},
        ),
        migrations.CreateModel(
            name="RoundMarketOutcome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_round_id", models.BigIntegerField(db_index=True)),
                ("phase_number", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="round_outcomes", to="Decision.character")),
                ("decision_round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resolved_outcomes", to="Decision.decisionround")),
                ("market", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resolved_outcomes", to="Decision.phasecharactermarket")),
                ("outcome", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="round_market_outcomes", to="Decision.outcome")),
            ],
            options={
                "db_table": "round_market_outcome",
                "ordering": ["-client_round_id", "character_id", "phase_number"],
            },
        ),
        migrations.CreateModel(
            name="MarketOdds",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_odds", models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ("market", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="odds", to="Decision.phasecharactermarket")),
                ("outcome", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="market_odds", to="Decision.outcome")),
            ],
            options={"db_table": "market_odds"},
        ),
        migrations.AddConstraint(
            model_name="phase",
            constraint=models.UniqueConstraint(fields=("round", "phase_number"), name="uniq_round_phase_number"),
        ),
        migrations.AddConstraint(
            model_name="phasecharactermarket",
            constraint=models.UniqueConstraint(fields=("round", "phase", "character"), name="uniq_round_phase_character_market"),
        ),
        migrations.AddConstraint(
            model_name="roundmarketoutcome",
            constraint=models.UniqueConstraint(fields=("client_round_id", "character", "phase_number"), name="uniq_client_round_character_phase_outcome"),
        ),
        migrations.AddConstraint(
            model_name="roundmarketoutcome",
            constraint=models.UniqueConstraint(fields=("client_round_id", "market"), name="uniq_client_round_market_outcome"),
        ),
        migrations.AddConstraint(
            model_name="marketodds",
            constraint=models.UniqueConstraint(fields=("market", "outcome"), name="uniq_market_outcome_odds"),
        ),
        migrations.RunPython(seed_outcomes, migrations.RunPython.noop),
    ]
