# Generated by Django 6.0.3 on 2026-03-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Bettor Analytics Dashboard',
                'verbose_name_plural': 'Bettor Analytics Dashboard',
                'managed': False,
            },
        ),
    ]
