"""
Django settings for decision_service project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from datetime import timedelta

from celery.schedules import crontab
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Allow importing sibling microservice "apps" (Generator, Gameplay) as Django apps.
_MICROSERVICES_DIR = BASE_DIR.parent
for _service_dir in (
    _MICROSERVICES_DIR / "odds_generator_service",
    _MICROSERVICES_DIR / "unity_gameplay_service",
):
    _service_path = str(_service_dir)
    if _service_path not in sys.path:
        sys.path.insert(0, _service_path)


def env_bool(name, default=False):
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-(7ba+0bf=7h9-14ci=^j$uc91xd8r0t*m=wh^ls1op4^4mo5ga",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'drf_spectacular',
    'Decision',
    'ml',
    'Generator.apps.OddsConfig',
    'Gameplay.apps.GameplayConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "decision_service.middleware.SafeHostMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "decision_service.middleware.AdminSSOMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'decision_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'decision_service.wsgi.application'
ASGI_APPLICATION = 'decision_service.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
      "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "DECISIONAPP"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "123456"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },
    "odds": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("ODDS_DB_NAME", "ODDSGENERATOR"),
        "USER": os.getenv("ODDS_DB_USER", os.getenv("DB_USER", "postgres")),
        "PASSWORD": os.getenv("ODDS_DB_PASSWORD", os.getenv("DB_PASSWORD", "123456")),
        "HOST": os.getenv("ODDS_DB_HOST", os.getenv("DB_HOST", "localhost")),
        "PORT": os.getenv("ODDS_DB_PORT", os.getenv("DB_PORT", "5432")),
    },
    "unity": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("UNITY_DB_NAME", "UNITYGAMEPLAY"),
        "USER": os.getenv("UNITY_DB_USER", os.getenv("DB_USER", "postgres")),
        "PASSWORD": os.getenv("UNITY_DB_PASSWORD", os.getenv("DB_PASSWORD", "123456")),
        "HOST": os.getenv("UNITY_DB_HOST", os.getenv("DB_HOST", "localhost")),
        "PORT": os.getenv("UNITY_DB_PORT", os.getenv("DB_PORT", "5432")),
    },
    "betting": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv(
            "BETS_DB_NAME",
            os.getenv("BETTING_DB_NAME", "CLIENTBETDATA"),
        ),
        "USER": os.getenv(
            "BETS_DB_USER",
            os.getenv("BETTING_DB_USER", os.getenv("DB_USER", "postgres")),
        ),
        "PASSWORD": os.getenv(
            "BETS_DB_PASSWORD",
            os.getenv("BETTING_DB_PASSWORD", os.getenv("DB_PASSWORD", "123456")),
        ),
        "HOST": os.getenv(
            "BETS_DB_HOST",
            os.getenv("BETTING_DB_HOST", os.getenv("DB_HOST", "localhost")),
        ),
        "PORT": os.getenv(
            "BETS_DB_PORT",
            os.getenv("BETTING_DB_PORT", os.getenv("DB_PORT", "5432")),
        ),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

SSO_SECRET = os.getenv("SSO_SECRET", "shared-secret-change-me")
FORCE_SCRIPT_NAME = os.getenv("FORCE_SCRIPT_NAME") or None
SSO_COOKIE_NAME = os.getenv("SSO_COOKIE_NAME", "admin_jwt")
LOGIN_URL = "/admin/login/"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Decision Service API',
    'DESCRIPTION': 'Betting decisions and round management',
    'VERSION': '1.0.0',
}

DATABASE_ROUTERS = ["decision_service.db_router.ServiceAppsRouter"]

# Unity gameplay defaults when hosted under decision_service.
UNITY_GAMEPLAY_BASE_PATH = os.getenv("UNITY_GAMEPLAY_BASE_PATH", "/gameplay")
UNITY_WEBGL_BUILD_URL = os.getenv("UNITY_WEBGL_BUILD_URL", "/gameplay/game2/")

CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    os.getenv("REDIS_URL", "redis://localhost:6379/0"),
)
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    CELERY_BROKER_URL,
)
CELERY_TIMEZONE = TIME_ZONE

CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL", os.getenv("REDIS_URL", "redis://localhost:6379/0")).strip()
if CHANNEL_REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [CHANNEL_REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

ROUND_TICK_SECONDS = max(1, int(os.getenv("ROUND_TICK_SECONDS", "5")))
CHARACTER_GENERATION_COUNT = max(1, int(os.getenv("CHARACTER_GENERATION_COUNT", "5")))
ODDS_SYNC_SECONDS = max(5, int(os.getenv("ODDS_SYNC_SECONDS", "120")))
ODDS_SYNC_LIMIT = max(1, int(os.getenv("ODDS_SYNC_LIMIT", "5")))

CELERY_BEAT_SCHEDULE = {
    "insert_characters_every_5_minutes": {
        "task": "Decision.tasks.insert_characters_task",
        "schedule": crontab(minute="*/5"),
        "kwargs": {"count": CHARACTER_GENERATION_COUNT},
    },
    "process_round_lifecycle": {
        "task": "Decision.tasks.process_round_lifecycle_task",
        "schedule": timedelta(seconds=ROUND_TICK_SECONDS),
    },
    "sync_latest_odds": {
        "task": "Generator.tasks.insert_latest_odds_task",
        "schedule": timedelta(seconds=ODDS_SYNC_SECONDS),
        "kwargs": {"limit": ODDS_SYNC_LIMIT},
    },
    "generate_sample_bettors_every_12_hours": {
        "task": "ml.tasks.generate_sample_bettors_task",
        "schedule": timedelta(hours=12),
    },
    "train_clustering_model_every_24_hours": {
        "task": "ml.tasks.train_clustering_model_task",
        "schedule": timedelta(hours=24),
    },
    "activate_latest_model_every_24_hours": {
        "task": "ml.tasks.activate_latest_model_task",
        "schedule": timedelta(hours=24, minutes=30),
    },
}



