# Generated by Django 6.0.3 on 2026-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGameplayState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=16)),
                ('tick', models.PositiveIntegerField(default=0)),
                ('max_ticks', models.PositiveIntegerField(default=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global gameplay state',
                'verbose_name_plural': 'Global gameplay state',
            },
        ),
        migrations.CreateModel(
            name='UnityGameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('build_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unity game config',
                'verbose_name_plural': 'Unity game configs',
                'ordering': ('-updated_at',),
            },
        ),
    ]
