# Generated by Django 6.0.3 on 2026-03-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnityGameplayDashboardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Unity Gameplay Dashboard',
                'verbose_name_plural': 'Unity Gameplay Dashboard',
                'db_table': 'unity_gameplay_dashboard_link',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
