# Generated by Django 6.0.3 on 2026-03-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField(db_index=True)),
                ('character', models.PositiveIntegerField()),
                ('game_round', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=12)),
                ('bet_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double')], db_index=True, max_length=8)),
                ('option_code', models.CharField(db_index=True, max_length=16)),
                ('phase_start', models.PositiveSmallIntegerField(db_index=True)),
                ('phase_end', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('placed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_bet',
                'ordering': ['-placed_at', '-id'],
                'indexes': [models.Index(fields=['player_id', 'placed_at'], name='idx_client_bet_player_ts'), models.Index(fields=['bet_type', 'placed_at'], name='idx_client_bet_type_ts'), models.Index(fields=['status', 'placed_at'], name='idx_client_bet_status_ts')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='chk_client_bet_status_valid'), models.CheckConstraint(condition=models.Q(('stake__gt', 0)), name='chk_client_bet_stake_gt_0'), models.CheckConstraint(condition=models.Q(('odds__gt', 1)), name='chk_client_bet_odds_gt_1'), models.CheckConstraint(condition=models.Q(('phase_start__gte', 1), ('phase_start__lte', 5)), name='chk_client_bet_phase_start_range_1_5'), models.CheckConstraint(condition=models.Q(('phase_end__isnull', True), models.Q(('phase_end__gte', 1), ('phase_end__lte', 5)), _connector='OR'), name='chk_client_bet_phase_end_range_1_5_or_null'), models.CheckConstraint(condition=models.Q(('phase_end__isnull', True), ('phase_end__gt', models.F('phase_start')), _connector='OR'), name='chk_client_bet_phase_end_gt_start')],
            },
        ),
        migrations.CreateModel(
            name='BetOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.BigIntegerField(db_index=True)),
                ('outcome_id', models.PositiveIntegerField(db_index=True)),
                ('selection_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'client_bet_outcome',
                'ordering': ['bet_id', 'selection_order'],
                'constraints': [models.UniqueConstraint(fields=('bet_id', 'selection_order'), name='uniq_client_bet_outcome_order'), models.UniqueConstraint(fields=('bet_id', 'outcome_id'), name='uniq_client_bet_outcome_pair'), models.CheckConstraint(condition=models.Q(('selection_order__gte', 1)), name='chk_client_bet_outcome_order_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.BigIntegerField(db_index=True, unique=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=12)),
            ],
            options={
                'db_table': 'client_game_round',
                'ordering': ['-round_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'CLOSED'])), name='chk_client_game_round_status_valid'), models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('end_time__gte', models.F('start_time')), _connector='OR'), name='chk_client_game_round_end_after_start_or_null'), models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='uniq_client_game_round_single_open')],
            },
        ),
        migrations.CreateModel(
            name='HouseWallet',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_house_wallet',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='chk_client_house_wallet_singleton_id_1')],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_outcome_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('phase_id', models.PositiveSmallIntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('FLOAT', 'Float'), ('DROWN', 'Drown')], max_length=8)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'client_outcome',
                'ordering': ['external_outcome_id'],
                'constraints': [models.UniqueConstraint(fields=('phase_id', 'kind'), name='uniq_client_outcome_phase_kind')],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'client_phase',
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 5)), name='chk_client_phase_number_range_1_5')],
            },
        ),
        migrations.CreateModel(
            name='PlayerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField(db_index=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_player_wallet',
                'ordering': ['player_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='chk_client_player_wallet_balance_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('bet_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('player_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('tx_type', models.CharField(choices=[('BET_STAKE', 'Bet Stake'), ('BET_PAYOUT', 'Bet Payout'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('from_account', models.CharField(choices=[('PLAYER', 'Player'), ('HOUSE', 'House'), ('SYSTEM', 'System')], max_length=8)),
                ('to_account', models.CharField(choices=[('PLAYER', 'Player'), ('HOUSE', 'House'), ('SYSTEM', 'System')], max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'client_wallet_transaction',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tx_type', 'created_at'], name='idx_client_wallet_tx_type_ts')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_client_wallet_tx_amount_gt_0')],
            },
        ),
    ]
