"""
Django settings for bettor_service project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Allow importing sibling microservice "apps" (Analytics, Betdata) as Django apps.
_MICROSERVICES_DIR = BASE_DIR.parent
for _service_dir in (
    _MICROSERVICES_DIR / "bettor_analytics_service",
    _MICROSERVICES_DIR / "bettors_bet_data_service",
):
    _service_path = str(_service_dir)
    if _service_path not in sys.path:
        sys.path.insert(0, _service_path)


def env_bool(name, default=False):
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-$*1mm4@@8%wgmt!(s9w49*t40s&xjvvi_-8=pwh@5r40pce=ge",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'Bettors.apps.BettorsConfig',
    'Analytics.apps.AnalyticsConfig',
    'Betdata.apps.BetdataConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "bettor_service.middleware.AdminSSOMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bettor_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bettor_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
     "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "BETTORS"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "Software"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },
    "demomoney": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DEMOMONEY_DB_NAME", "DEMOMONEY"),
        "USER": os.getenv("DEMOMONEY_DB_USER", os.getenv("DB_USER", "postgres")),
        "PASSWORD": os.getenv("DEMOMONEY_DB_PASSWORD", os.getenv("DB_PASSWORD", "Software")),
        "HOST": os.getenv("DEMOMONEY_DB_HOST", os.getenv("DB_HOST", "localhost")),
        "PORT": os.getenv("DEMOMONEY_DB_PORT", os.getenv("DB_PORT", "5432")),
    },
    "betdata": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("BETDATA_DB_NAME", os.getenv("DB_BETDATA_NAME", "CLIENTBETDATA")),
        "USER": os.getenv("BETDATA_DB_USER", os.getenv("DB_USER", "postgres")),
        "PASSWORD": os.getenv("BETDATA_DB_PASSWORD", os.getenv("DB_PASSWORD", "Software")),
        "HOST": os.getenv("BETDATA_DB_HOST", os.getenv("DB_HOST", "localhost")),
        "PORT": os.getenv("BETDATA_DB_PORT", os.getenv("DB_PORT", "5432")),
    },
    "analytics": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("ANALYTICS_DB_NAME", os.getenv("DB_ANALYTICS_NAME", "BETTORANALYTICS")),
        "USER": os.getenv("ANALYTICS_DB_USER", os.getenv("DB_USER", "postgres")),
        "PASSWORD": os.getenv("ANALYTICS_DB_PASSWORD", os.getenv("DB_PASSWORD", "Software")),
        "HOST": os.getenv("ANALYTICS_DB_HOST", os.getenv("DB_HOST", "localhost")),
        "PORT": os.getenv("ANALYTICS_DB_PORT", os.getenv("DB_PORT", "5432")),
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
SSO_SECRET = os.getenv("SSO_SECRET", "shared-secret-change-me")
FORCE_SCRIPT_NAME = os.getenv("FORCE_SCRIPT_NAME") or None
SSO_COOKIE_NAME = os.getenv("SSO_COOKIE_NAME", "admin_jwt")
LOGIN_URL = "/admin/login/"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env_bool("USE_X_FORWARDED_HOST", True)

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Bettor Service API',
    'DESCRIPTION': 'Bettor management and operations',
    'VERSION': '1.0.0',
}

DATABASE_ROUTERS = ["bettor_service.db_router.ServiceAppsRouter"]
