CREATE DATABASE "ADMINPORTAL";
CREATE DATABASE "DECISIONAPP";
CREATE DATABASE "UNITYGAMEPLAY";
CREATE DATABASE "BETTORS";
CREATE DATABASE "BETTORANALYTICS";
CREATE DATABASE "CLIENTBETDATA";
CREATE DATABASE "ODDSGENERATOR";
CREATE DATABASE "DEMOMONEY";
