# Generated by Django 6.0.3 on 2026-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bettors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=60)),
                ('id_number', models.BigIntegerField()),
                ('physical_address', models.TextField()),
                ('password_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
