# Generated by Django 5.2.13 on 2026-04-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bettors', '0002_demo_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettors',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='demomoney',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
