# Generated by Django 6.0.3 on 2026-03-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('drn1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drn2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drn3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drn4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drn5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt1_and_drn2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt1_and_drn3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt1_and_drn4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt1_and_drn5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt2_and_drn3', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt2_and_drn4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt2_and_drn5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt3_and_drn4', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt3_and_drn5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('flt4_and_drn5', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bet_odds',
            },
        ),
        migrations.DeleteModel(
            name='Bet_decision',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AddConstraint(
            model_name='betodds',
            constraint=models.UniqueConstraint(fields=('character_id',), name='uniq_bet_odds_character'),
        ),
    ]
