# Generated by Django 5.2.13 on 2026-04-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Generator', '0002_betodds_delete_bet_decision_delete_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betodds',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
