from django.urls import path, re_path, include
from rest_framework.routers import DefaultRouter

from . import views

# =============================================================================
# URL CONFIGURATION - OPTIMIZED
# =============================================================================

# Pre-compute service ID alternation pattern at import time (static data → compute once)
# Creates efficient regex alternation: (decision|gameplay|bettor|analytics|betdata|odds)
_SERVICE_IDS = '|'.join(views.MICROSERVICES.keys())

# Pre-built regex patterns for dynamic forwarding
# Django compiles these once at startup, not per-request
# Optimization: Removed redundant capturing group: (?P<name>(...)) → (?P<name>...)
_FORWARD_PATTERN = f'^(?P<service_id>{_SERVICE_IDS})/(?P<path>.*)$'
_FORWARD_PREFIXED_PATTERN = f'^services/(?P<service_id>{_SERVICE_IDS})/(?P<path>.*)$'

# Initialize router for GatewayViewSet (handles /gateway/ namespace routes)
router = DefaultRouter()
router.register(r'gateway', views.GatewayViewSet, basename='gateway')

# URL patterns ordered by expected access frequency (Django matches top-to-bottom)
# Static path() patterns are faster than regex re_path() → use where possible
urlpatterns = [
    # Root endpoint - most frequent, simple path() for fastest matching
    path('', views.api_root, name='api-root'),
    
    # Gateway ViewSet routes (auto-generated by router):
    # - GET /gateway/ → list services
    # - GET/POST/... /gateway/{pk}/forward/{path}/ → forward action
    # - GET /gateway/{pk}/health/ → health action
    path('gateway/', include(router.urls)),
    
    # Explicit health endpoint for direct access (avoids router resolution overhead)
    # Matches: /gateway/decision/health/ → views.service_health
    path('gateway/<str:service_id>/health/', views.service_health, name='service-health'),
    
    # Dynamic service forwarding: /decision/users/123 → forwards to decision service
    # Optimized regex with pre-computed service ID alternation (no runtime string ops)
    re_path(_FORWARD_PATTERN, views.forward_to_service, name='service-forward'),
    
    # Alternative prefixed route for backward compatibility: /services/decision/users/
    re_path(_FORWARD_PREFIXED_PATTERN, views.forward_to_service, name='service-forward-prefixed'),
]