# Generated by Django 6.0.4 on 2026-04-19 12:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('n_clusters', models.PositiveSmallIntegerField()),
                ('random_state', models.PositiveIntegerField(default=42)),
                ('max_iterations', models.PositiveIntegerField(default=300)),
                ('n_init', models.PositiveIntegerField(default=10)),
                ('num_samples_trained', models.PositiveIntegerField()),
                ('features_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='List of feature names used for clustering')),
                ('inertia', models.FloatField(blank=True, null=True)),
                ('silhouette_score', models.FloatField(blank=True, null=True)),
                ('davies_bouldin_score', models.FloatField(blank=True, null=True)),
                ('model_params', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('last_evaluated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clustering_models',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='BettorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bettor_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('total_bets', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('total_losses', models.PositiveIntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('average_bet_amount', models.FloatField(default=0.0)),
                ('max_bet_amount', models.FloatField(default=0.0)),
                ('min_bet_amount', models.FloatField(default=0.0)),
                ('bet_variance', models.FloatField(default=0.0)),
                ('average_bets_per_round', models.FloatField(default=0.0)),
                ('total_active_rounds', models.PositiveIntegerField(default=0)),
                ('favorite_bet_type', models.CharField(blank=True, max_length=50)),
                ('strategy_diversity', models.FloatField(default=0.0)),
                ('total_profit', models.FloatField(default=0.0)),
                ('roi', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bettor_profiles',
                'indexes': [models.Index(fields=['bettor_id', 'last_updated'], name='bettor_prof_bettor__0242e4_idx'), models.Index(fields=['win_rate'], name='bettor_prof_win_rat_ca3520_idx'), models.Index(fields=['roi'], name='bettor_prof_roi_8451ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('accuracy', 'Accuracy'), ('precision', 'Precision'), ('recall', 'Recall'), ('silhouette', 'Silhouette Score'), ('davies_bouldin', 'Davies-Bouldin Index'), ('inertia', 'Inertia')], max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ml.clusteringmodel')),
            ],
            options={
                'db_table': 'ml_metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClusterCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('centroid', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField())),
                ('cluster_size', models.PositiveIntegerField()),
                ('avg_win_rate', models.FloatField()),
                ('avg_roi', models.FloatField()),
                ('avg_bet_amount', models.FloatField()),
                ('avg_strategy_diversity', models.FloatField()),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('profile_description', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_characteristics', to='ml.clusteringmodel')),
            ],
            options={
                'db_table': 'cluster_characteristics',
                'unique_together': {('model', 'cluster_id')},
            },
        ),
        migrations.CreateModel(
            name='BettorCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.PositiveSmallIntegerField()),
                ('confidence', models.FloatField(default=0.0)),
                ('feature_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Feature vector used for this clustering assignment')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bettor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to='ml.bettorprofile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bettor_clusters', to='ml.clusteringmodel')),
            ],
            options={
                'db_table': 'bettor_clusters',
                'indexes': [models.Index(fields=['model', 'cluster_id'], name='bettor_clus_model_i_aec4b6_idx'), models.Index(fields=['bettor_profile', 'model'], name='bettor_clus_bettor__623c67_idx')],
                'unique_together': {('model', 'bettor_profile')},
            },
        ),
    ]
