# Generated by Django 6.0.4 on 2026-04-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_round_betting_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='betoptionknowledgerow',
            new_name='bet_option__version_dd3343_idx',
            old_name='bet_option__version_8f8c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='betoptionknowledgerow',
            new_name='bet_option__version_5fc0d6_idx',
            old_name='bet_option__version_f79ed0_idx',
        ),
    ]
